#!/bin/bash

container_id=$(docker ps -a --format "{{.ID}} {{.Names}}" \
  | fzf --prompt="Select container to view logs: " \
  | awk '{print $1}')

# 選択されなければ終了
if [[ -z "$container_id" ]]; then
  echo "No container selected."
  exit 1
fi

docker logs "$container_id"